"""Public API DTOs. The web app talks only to these normalized shapes."""

from datetime import datetime
from decimal import Decimal
from typing import Any

from cmc_shared.enums import (
    ActionStatus,
    ActionType,
    AgentMode,
    CartStatus,
    ConnectionStatus,
    DomainEventType,
    EntityType,
    ErrorCode,
    MessageDirection,
    MessageStatus,
    NotificationType,
    OrderStatus,
    PaymentStatus,
    ShippingStatus,
    SyncEntity,
    SyncRunStatus,
    UserRole,
)
from pydantic import BaseModel, ConfigDict, EmailStr, Field, field_validator


class ORM(BaseModel):
    model_config = ConfigDict(from_attributes=True)


class Page[T](BaseModel):
    items: list[T]
    total: int
    limit: int
    offset: int


class OkResponse(BaseModel):
    ok: bool = True


# --------------------------------------------------------------------- auth


class LoginRequest(BaseModel):
    email: EmailStr
    password: str = Field(min_length=1, max_length=256)


class UserOut(ORM):
    id: int
    email: str
    name: str
    role: UserRole
    active: bool
    last_login_at: datetime | None
    created_at: datetime


class MeOut(UserOut):
    permissions: list[str]


class ChangePasswordRequest(BaseModel):
    current_password: str = Field(max_length=256)
    new_password: str = Field(min_length=10, max_length=256)


class SetupStatus(BaseModel):
    needs_admin: bool
    mock_mode: bool
    push_enabled: bool
    connection_status: ConnectionStatus
    agent_online: bool
    has_synced: bool
    # "open": wizard usable; "token": a setup token is required; "disabled":
    # create the administrator from the command line (app.scripts.create_admin).
    web_setup: str


class SetupAdminRequest(BaseModel):
    email: EmailStr
    name: str = Field(min_length=1, max_length=120)
    password: str = Field(min_length=10, max_length=256)
    setup_token: str | None = Field(default=None, max_length=256)


class UserCreate(BaseModel):
    email: EmailStr
    name: str = Field(min_length=1, max_length=120)
    role: UserRole = UserRole.STAFF
    password: str = Field(min_length=10, max_length=256)


class UserUpdate(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=120)
    role: UserRole | None = None
    active: bool | None = None
    password: str | None = Field(default=None, min_length=10, max_length=256)


# ------------------------------------------------------------------- orders


class ItemOut(ORM):
    id: int
    card_name: str
    expansion: str | None
    language: str | None
    condition: str | None
    quantity: int
    unit_price: Decimal | None
    total_price: Decimal | None


class OrderListItem(ORM):
    id: int
    cardmarket_id: str
    buyer_name: str
    status: OrderStatus
    payment_status: PaymentStatus
    shipping_status: ShippingStatus
    total_amount: Decimal | None
    currency: str
    item_count: int | None
    order_date: datetime | None
    paid_at: datetime | None
    shipped_at: datetime | None
    is_new: bool
    last_seen_at: datetime


class ConversationRef(ORM):
    id: int
    unread: bool
    last_message_at: datetime | None


class OrderDetail(OrderListItem):
    tracking_number: str | None
    raw_source_reference: str | None
    detail_fetched_at: datetime | None
    items: list[ItemOut]
    conversations: list[ConversationRef]
    pending_action: "ActionBrief | None" = None


class ShipOrderRequest(BaseModel):
    tracking_number: str | None = Field(default=None, max_length=80)
    client_key: str = Field(min_length=8, max_length=64)


# ------------------------------------------------------------ conversations


class MessageOut(ORM):
    id: int
    direction: MessageDirection
    sender: str
    body: str
    sent_at: datetime | None
    status: MessageStatus
    created_at: datetime
    action_id: int | None


class OrderRef(ORM):
    id: int
    cardmarket_id: str
    status: OrderStatus
    total_amount: Decimal | None
    currency: str


class ConversationListItem(ORM):
    id: int
    cardmarket_id: str
    buyer_name: str
    unread: bool
    last_message_at: datetime | None
    last_message_preview: str | None
    order: OrderRef | None


class ConversationDetail(ConversationListItem):
    messages: list[MessageOut]
    raw_source_reference: str | None


class SendMessageRequest(BaseModel):
    body: str = Field(min_length=1, max_length=4000)
    # Generated by the client once per composed message: resubmits are idempotent.
    client_key: str = Field(min_length=8, max_length=64)

    @field_validator("body")
    @classmethod
    def _strip(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Il messaggio è vuoto")
        return value


# -------------------------------------------------------------------- carts


class CartListItem(ORM):
    id: int
    cardmarket_id: str
    buyer_name: str
    status: CartStatus
    total_amount: Decimal | None
    currency: str
    item_count: int | None
    cardmarket_created_at: datetime | None
    created_at: datetime
    updated_at: datetime
    last_seen_at: datetime


class CartDetail(CartListItem):
    items: list[ItemOut]
    raw_source_reference: str | None


# ------------------------------------------------------------ notifications


class NotificationOut(ORM):
    id: int
    type: NotificationType
    title: str
    body: str
    entity_type: EntityType | None
    entity_id: int | None
    read: bool
    created_at: datetime
    link: str


class NotificationPreferenceOut(BaseModel):
    type: NotificationType
    in_app: bool
    push: bool


class NotificationPreferencesUpdate(BaseModel):
    preferences: list[NotificationPreferenceOut]


class PushSubscriptionIn(BaseModel):
    endpoint: str = Field(min_length=10, max_length=2000)
    keys: dict[str, str]


class PushConfigOut(BaseModel):
    enabled: bool
    public_key: str | None


# ---------------------------------------------------------------- templates


class TemplateOut(ORM):
    id: int
    key: str
    label: str
    icon: str
    body: str
    position: int
    active: bool


class TemplateIn(BaseModel):
    key: str = Field(min_length=1, max_length=60, pattern=r"^[a-z0-9_\-]+$")
    label: str = Field(min_length=1, max_length=80)
    icon: str = Field(default="", max_length=16)
    body: str = Field(min_length=1, max_length=4000)
    position: int = 0
    active: bool = True


class TemplateRenderRequest(BaseModel):
    conversation_id: int | None = None
    order_id: int | None = None
    tracking_number: str | None = Field(default=None, max_length=80)


class TemplateRenderOut(BaseModel):
    text: str
    missing_variables: list[str]


# ------------------------------------------------------ connection / agent


class ConnectionOut(BaseModel):
    status: ConnectionStatus
    agent_online: bool
    agent_mode: AgentMode | None
    agent_version: str | None
    agent_last_seen_at: datetime | None
    agent_detail: str | None
    last_successful_sync: datetime | None
    last_authentication: datetime | None
    last_error: str | None
    last_error_code: ErrorCode | None
    last_error_at: datetime | None
    status_changed_at: datetime | None
    sync_running: bool
    session_paired_at: datetime | None
    session_last_verified_at: datetime | None
    pending_session_action: "ActionBrief | None"
    mock_mode: bool
    pairing_viewer_url: str | None


class ActionBrief(ORM):
    id: int
    type: ActionType
    status: ActionStatus
    created_at: datetime
    attempts: int
    last_error: str | None


class ActionOut(ActionBrief):
    payload: dict[str, Any]
    max_attempts: int
    last_error_code: ErrorCode | None
    result: dict[str, Any]
    needs_verification: bool
    correlation_id: str | None
    requested_by_user_id: int | None
    not_before: datetime | None
    started_at: datetime | None
    completed_at: datetime | None


class SyncRunOut(ORM):
    id: int
    sync_id: str
    started_at: datetime
    completed_at: datetime | None
    status: SyncRunStatus
    entity_type: SyncEntity
    trigger: str
    records_found: int
    records_changed: int
    error: str | None
    error_code: ErrorCode | None
    artifacts: list[str]


class SyncStatusOut(BaseModel):
    sync_enabled: bool
    sync_interval_seconds: int
    last_successful_sync: datetime | None
    running: bool
    last_runs: list[SyncRunOut]


class AuditLogOut(ORM):
    id: int
    user_id: int | None
    actor: str
    action: str
    entity_type: EntityType | None
    entity_id: str | None
    result: str
    error: str | None
    details: dict[str, Any]
    ip: str | None
    request_id: str | None
    created_at: datetime


class RuntimeSettingsOut(BaseModel):
    sync_enabled: bool
    sync_interval_seconds: int
    shop_name: str


class RuntimeSettingsUpdate(BaseModel):
    sync_enabled: bool | None = None
    sync_interval_seconds: int | None = Field(default=None, ge=10, le=3600)
    shop_name: str | None = Field(default=None, max_length=80)


class SimulationRequest(BaseModel):
    scenario: str = Field(pattern=r"^(session_expired|sync_error|new_activity)$")


class PurgeRequest(BaseModel):
    confirm: str


class ErrorsOut(BaseModel):
    sync_runs: list[SyncRunOut]
    actions: list[ActionOut]
    connection_error: str | None
    connection_error_code: ErrorCode | None


class ActivityItem(BaseModel):
    id: int
    type: DomainEventType
    title: str
    occurred_at: datetime
    link: str | None


class DashboardConnection(BaseModel):
    status: ConnectionStatus
    agent_online: bool
    agent_mode: AgentMode | None
    last_successful_sync: datetime | None
    last_error: str | None
    last_error_code: ErrorCode | None


class DashboardOrders(BaseModel):
    new: int
    to_ship: int
    unpaid: int
    paid_24h: int


class DashboardMessages(BaseModel):
    unread_conversations: int


class DashboardCarts(BaseModel):
    to_pay: int
    paid: int


class SalesRow(BaseModel):
    currency: str
    total: Decimal
    orders: int


class DashboardSales(BaseModel):
    window_days: int
    by_currency: list[SalesRow]


class DashboardAttention(BaseModel):
    failed_syncs_24h: int
    actions_needing_attention: int
    failed_actions_24h: int


class DashboardOut(BaseModel):
    connection: DashboardConnection
    orders: DashboardOrders
    messages: DashboardMessages
    carts: DashboardCarts
    sales: DashboardSales
    attention: DashboardAttention
    notifications_unread: int
    activity: list[ActivityItem]
    generated_at: datetime


OrderDetail.model_rebuild()
ConnectionOut.model_rebuild()
